services:
  mongo:
    image: mongo:6
    container_name: mlops-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  import_csv:
    build:
      context: .
      dockerfile: batch/Dockerfile
    container_name: batch-import
    volumes:
      - ./batch/input_mock_data:/app/batch/input_mock_data
      - ./common:/app/common
    environment:
      - MONGO_URI=${MONGO_URI}
    depends_on:
      - mongo
    command: python batch/import_csv_runner.py

  batch:
    build:
      context: . # ⬅️ Use the root folder as build context
      dockerfile: batch/Dockerfile
    container_name: mlops-batch
    volumes:
      - ./model:/app/model
      - ./common:/app/common
      - ./logs:/app/logs
    depends_on:
      - mongo
    environment:
      - MONGO_URI=${MONGO_URI}
    command: python batch/batch_runner.py

  api:
    build:
      context: . # ⬅️ Use the root folder as build context
      dockerfile: api/Dockerfile
    container_name: mlops-api
    ports:
      - "5000:5000"
    volumes:
      - ./api:/app/api
      - ./common:/app/common
      - ./model:/app/model
    command: python api/app.py

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.0
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.13.0
    container_name: filebeat
    user: root
    volumes:
      - ./logs:/usr/share/filebeat/logs
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
    depends_on:
      - elasticsearch

volumes:
  mongo_data:
  esdata:
