filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /usr/share/filebeat/logs/*.log

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  username: ""
  password: ""

setup.kibana:
  host: "kibana:5601"

logging.level: info
